{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-gpu-monitoring-dev.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-gpu-monitoring-dev.frontend.labels" . | nindent 4 }}
  {{- with (include "k8s-gpu-monitoring-dev.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "k8s-gpu-monitoring-dev.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-gpu-monitoring-dev.frontend.labels" . | nindent 8 }}
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.frontend.securityContext | nindent 8 }}
      containers:
      - name: frontend
        image: {{ include "k8s-gpu-monitoring-dev.frontend.image" . }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.frontend.containerPort }}
          protocol: TCP
        securityContext:
          {{- toYaml .Values.frontend.containerSecurityContext | nindent 10 }}
        env:
        - name: API_BASE_URL
          value: "http://{{ include "k8s-gpu-monitoring-dev.backend.fullname" . }}:{{ .Values.backend.service.port }}"
        {{- range $key, $value := .Values.frontend.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- with .Values.frontend.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.frontend.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 