name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [backend, frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          echo "Initial disk usage:"
          df -h
          # Remove unnecessary files to free up space
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker system prune -af
          echo "After cleanup:"
          df -h

      - name: Get version from tag
        id: get_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.component }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.component }}
          file: ./${{ matrix.component }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          provenance: false

  helm:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Get version from tag
        id: get_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Verify Chart version consistency
        run: |
          CHART_VERSION=$(grep "version:" ./charts/k8s-gpu-monitoring-dev/Chart.yaml | awk '{print $2}')
          CHART_APP_VERSION=$(grep "appVersion:" ./charts/k8s-gpu-monitoring-dev/Chart.yaml | awk '{print $2}' | tr -d '"')
          
          echo "Verifying version consistency..."
          echo "  Release version: ${{ steps.get_version.outputs.version }}"
          echo "  Chart version: $CHART_VERSION"
          echo "  Chart appVersion: $CHART_APP_VERSION"
          
          if [ "$CHART_VERSION" != "${{ steps.get_version.outputs.version }}" ] || [ "$CHART_APP_VERSION" != "${{ steps.get_version.outputs.version }}" ]; then
            echo "ERROR: Version mismatch detected!"
            echo "Please update Chart.yaml with the correct version before creating the tag."
            echo "  Chart version should be: ${{ steps.get_version.outputs.version }}"
            echo "  Chart appVersion should be: ${{ steps.get_version.outputs.version }}"
            exit 1
          fi
          
          echo "All versions are consistent!"

      - name: Update values.yaml with new image tags
        run: |
          # Update backend and frontend image tags in values.yaml
          sed -i 's/tag: ".*"/tag: "${{ steps.get_version.outputs.version }}"/g' ./charts/k8s-gpu-monitoring-dev/values.yaml
          
          echo "Updated values.yaml with version ${{ steps.get_version.outputs.version }}"
          grep -A 3 'image:' ./charts/k8s-gpu-monitoring-dev/values.yaml

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}" 